# -*- coding: utf-8 -*-
"""retail_profit_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cB47eARdvUYLl-ZW5PzTyFe70FlVj2Ut

#**Superstore Profit Analysis**
"""

import pandas as pd

df = pd.read_csv("Superstore.csv", encoding='latin1')

df.head()

df.shape

df.info

df.describe

df.isnull().sum()

df.duplicated().sum()

df.describe()

df.columns

"""#**Profit Analysis**

This section examines the store’s profitability from multiple angles. We begin by calculating the total profit to see the overall earnings, then break it down by product category, region, and sub-category. This helps identify which products and areas contribute most to revenue and provides insights for improving business performance.
"""

total_profit = df['Profit'].sum()
print("Total Profit of the store: $", total_profit)

"""***Profit by Product Category***

Identify the product categories that generate the highest profit.
"""

# Total profit for each product category
profit_by_category = df.groupby('Category')['Profit'].sum()

print("Profit by Product Category:")
print(profit_by_category)

# the category with the most profit
top_category = profit_by_category.idxmax()
top_profit = profit_by_category.max()

print("\nThe product category that made the most profit is:", top_category)
print("It made a total profit of $", round(top_profit, 2))

"""***Profit by Region***

Determine which geographical regions contribute the most to overall profitability.
"""

# Total profit by Region
profit_by_region = df.groupby('Region')['Profit'].sum()

# Print all region profits
print("Profit by Region:")
print(profit_by_region)

#the region with the most profit
top_region = profit_by_region.idxmax()
top_region_profit = profit_by_region.max()

print("\nThe region that made the most profit is:", top_region)
print("It made a total profit of $", round(top_region_profit, 2))

"""***Profit by Sub-Category***

Analysing specific product groups to understand which perform best financially.
"""

# Total profit by Sub-Category
profit_by_subcategory = df.groupby('Sub-Category')['Profit'].sum()

# Print all sub-category profits
print("Profit by Sub-Category:")
print(profit_by_subcategory)

# the sub-category with the most profit
top_subcategory = profit_by_subcategory.idxmax()
top_subcategory_profit = profit_by_subcategory.max()

print("\nThe sub-category that made the most profit is:", top_subcategory)
print("It made a total profit of $", round(top_subcategory_profit, 2))

with pd.ExcelWriter("Superstore_Analysis_Report.xlsx") as writer:
    profit_by_category.to_excel(writer, sheet_name="By Category", index=False)
    profit_by_region.to_excel(writer, sheet_name="By Region", index=False)
    profit_by_subcategory.to_excel(writer, sheet_name="By Sub-Category", index=False)

from google.colab import files

files.download("Superstore_Analysis_Report.xlsx")

profit_by_category

profit_by_category = df.groupby('Category')['Profit'].sum().reset_index()

profit_by_region = df.groupby('Region')['Profit'].sum().reset_index()

profit_by_subcategory = df.groupby('Sub-Category')['Profit'].sum().reset_index()

df['Category'].unique()

profit_by_category = df.groupby('Category')['Profit'].sum().reset_index()

profit_by_region = df.groupby('Region')['Profit'].sum().reset_index()

profit_by_subcategory = df.groupby('Sub-Category')['Profit'].sum().reset_index()

profit_by_category

with pd.ExcelWriter("Superstore_Analysis_Report.xlsx") as writer:
    profit_by_category.to_excel(writer, sheet_name="By Category", index=False)
    profit_by_region.to_excel(writer, sheet_name="By Region", index=False)
    profit_by_subcategory.to_excel(writer, sheet_name="By Sub-Category", index=False)

from google.colab import files

files.download("Superstore_Analysis_Report.xlsx")

